project:
  type: website
  resources:
    - "www/*"
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Coding Summer 2025"
  site-url: https://Imbernoulli.github.io/summer/
  description: "暑期代码能力提升培训"
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: master
  repo-url: https://github.com/Imbernoulli/summer
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/Imbernoulli/summer
  sidebar:
    style: "floating"
  resources:
    - "resources"

metadata-files:
  - sidebar.yml
